import type { Metadata } from "next";
import { ThemeProvider } from "@/components/context/ThemeProvider";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";
import RQProvider from "@/components/context/RQProvider";
import SmoothScrollProvider from "@/components/context/SmoothScrollProvider";

import NextTopLoader from 'nextjs-toploader';

const inter = Inter({ subsets: ["latin"] });


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NextTopLoader />
        <SmoothScrollProvider />
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Header />
          <RQProvider>
            {children}
          </RQProvider>
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
